name: First Workflow

#Trigger when workflow will run

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one line script
      run: echo Hello,World
