name: Second Workflow
on:
  workflow_dispatch:
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: print 1 
      run: echo "I am running from Runner"
    - name: print 2
      run: echo "Good bye for now"
